# Numpy crash course

In [1]:
import numpy as np

In [2]:
np.__version__ 

'2.4.6'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.arange(10,50,5) 

array([10, 15, 20, 25, 30, 35, 40, 45])

In [9]:
np.arange(10,50,5,1) 

TypeError: Cannot interpret '1' as a data type

In [10]:
np.arange(20, 10) 

array([], dtype=int64)

In [11]:
np.arange(-20, 10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [12]:
np.zeros(3, dtype=float)  #1d array (parameter tunning) 

array([0., 0., 0.])

In [13]:
np.zeros(3, dtype=int)  #1d array (hyperparameer tunning) 

array([0, 0, 0])

In [14]:
np.zeros([2,2]) #2d array

array([[0., 0.],
       [0., 0.]])

In [15]:
np.zeros([10,10], dtype=int) #nd array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
np.ones(4) 

array([1., 1., 1., 1.])

In [17]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [18]:
np.two(3)

AttributeError: module 'numpy' has no attribute 'two'

In [19]:
np.rand(3)

AttributeError: module 'numpy' has no attribute 'rand'

In [20]:
np.random.rand(3)

array([0.6113973 , 0.33347733, 0.54011427])

In [21]:
np.random.rand(3,4) 

array([[0.66143169, 0.57573268, 0.92844018, 0.91707517],
       [0.92933753, 0.00171561, 0.58784913, 0.00376028],
       [0.8209736 , 0.05043   , 0.83350056, 0.02559922]])

In [22]:
np.random.randint(3)

1

In [23]:
np.random.randint(10,20)

12

In [24]:
np.random.randint(1,10,4) 

array([2, 9, 1, 5], dtype=int32)

In [25]:
print(np.random.randint(1,10,4)) 

[8 3 9 1]


In [26]:
m = np.random.randint(1,10,(4,6))
print(m)

[[1 7 8 3 5 7]
 [1 8 3 2 6 1]
 [5 9 3 6 1 9]
 [1 8 2 8 3 1]]


In [27]:
# indexiing & slicing in array 

In [28]:
print(m)

[[1 7 8 3 5 7]
 [1 8 3 2 6 1]
 [5 9 3 6 1 9]
 [1 8 2 8 3 1]]


In [29]:
m[0] 

array([1, 7, 8, 3, 5, 7], dtype=int32)

In [30]:
m[0] = [4,5,6,7,8,9]

In [31]:
m


array([[4, 5, 6, 7, 8, 9],
       [1, 8, 3, 2, 6, 1],
       [5, 9, 3, 6, 1, 9],
       [1, 8, 2, 8, 3, 1]], dtype=int32)

In [32]:
m[2]

array([5, 9, 3, 6, 1, 9], dtype=int32)

In [33]:
m[-3]

array([1, 8, 3, 2, 6, 1], dtype=int32)

In [34]:
m


array([[4, 5, 6, 7, 8, 9],
       [1, 8, 3, 2, 6, 1],
       [5, 9, 3, 6, 1, 9],
       [1, 8, 2, 8, 3, 1]], dtype=int32)

In [35]:
print(m[0,4])

8


In [36]:
m

array([[4, 5, 6, 7, 8, 9],
       [1, 8, 3, 2, 6, 1],
       [5, 9, 3, 6, 1, 9],
       [1, 8, 2, 8, 3, 1]], dtype=int32)

In [37]:
print(m[-2, -3])

6


In [38]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [40]:
b = np.random.randint(10,20,(5,4))
b

array([[18, 12, 11, 14],
       [13, 19, 11, 11],
       [12, 15, 16, 15],
       [14, 10, 12, 17],
       [11, 13, 17, 18]], dtype=int32)

In [41]:
type(b)

numpy.ndarray

In [42]:
b


array([[18, 12, 11, 14],
       [13, 19, 11, 11],
       [12, 15, 16, 15],
       [14, 10, 12, 17],
       [11, 13, 17, 18]], dtype=int32)

In [43]:
b[:] 

array([[18, 12, 11, 14],
       [13, 19, 11, 11],
       [12, 15, 16, 15],
       [14, 10, 12, 17],
       [11, 13, 17, 18]], dtype=int32)

In [44]:
b[1:3]

array([[13, 19, 11, 11],
       [12, 15, 16, 15]], dtype=int32)

In [45]:
b[1,2]

np.int32(11)

In [46]:
b[1,3]

np.int32(11)

In [47]:
b[1,-1]

np.int32(11)

In [48]:
b[2:3]

array([[12, 15, 16, 15]], dtype=int32)

In [49]:
b[0:-2] 

array([[18, 12, 11, 14],
       [13, 19, 11, 11],
       [12, 15, 16, 15]], dtype=int32)

In [50]:
b[0,2] 

np.int32(11)

In [51]:
b[-5,-3] 

np.int32(12)

In [52]:
b[-4,2] 

np.int32(11)

In [53]:
np.random.randint(10,20,(4,4))

array([[12, 12, 15, 13],
       [12, 18, 12, 19],
       [12, 12, 13, 18],
       [17, 10, 11, 17]], dtype=int32)

In [54]:
b 

array([[18, 12, 11, 14],
       [13, 19, 11, 11],
       [12, 15, 16, 15],
       [14, 10, 12, 17],
       [11, 13, 17, 18]], dtype=int32)

In [55]:
b[-4,-2]

np.int32(11)

In [56]:
b[-4:2] 

array([[13, 19, 11, 11]], dtype=int32)

In [57]:
b[:]

array([[18, 12, 11, 14],
       [13, 19, 11, 11],
       [12, 15, 16, 15],
       [14, 10, 12, 17],
       [11, 13, 17, 18]], dtype=int32)

## Operations

In [58]:
a = np.random.randint(10,20,10)
a

array([11, 11, 14, 17, 14, 17, 16, 10, 15, 13], dtype=int32)

In [59]:
id(a)

1639761690864

In [60]:
arr

array([0, 1, 2, 3, 4, 5])

In [61]:
arr2 = np.random.randint(0,100,(10,10))

In [62]:
arr2

array([[64, 53, 73, 65, 53, 26, 16, 34, 25, 38],
       [80, 51, 52,  3, 94, 77,  8, 75, 75, 22],
       [10, 90, 28, 29, 48,  7, 88,  0, 43,  1],
       [16,  6, 37, 22, 54, 23, 97, 12, 20, 80],
       [63, 97, 48, 35, 79, 37, 85, 88, 13, 33],
       [73, 19, 95, 76, 23, 98, 66, 13, 99,  0],
       [52,  3, 49, 53, 25, 61, 40, 94, 30, 79],
       [14, 10, 26, 90, 79, 34, 12, 86, 91,  6],
       [87, 60, 39, 33, 17, 52, 37, 36, 16, 44],
       [ 5, 70, 65, 19, 56,  4, 51, 65, 88, 89]], dtype=int32)

In [63]:
arr

array([0, 1, 2, 3, 4, 5])

In [64]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [65]:
arr

array([0, 1, 2, 3, 4, 5])

In [66]:
arr[:4] 

array([0, 1, 2, 3])

In [67]:
arr2[:]

array([[64, 53, 73, 65, 53, 26, 16, 34, 25, 38],
       [80, 51, 52,  3, 94, 77,  8, 75, 75, 22],
       [10, 90, 28, 29, 48,  7, 88,  0, 43,  1],
       [16,  6, 37, 22, 54, 23, 97, 12, 20, 80],
       [63, 97, 48, 35, 79, 37, 85, 88, 13, 33],
       [73, 19, 95, 76, 23, 98, 66, 13, 99,  0],
       [52,  3, 49, 53, 25, 61, 40, 94, 30, 79],
       [14, 10, 26, 90, 79, 34, 12, 86, 91,  6],
       [87, 60, 39, 33, 17, 52, 37, 36, 16, 44],
       [ 5, 70, 65, 19, 56,  4, 51, 65, 88, 89]], dtype=int32)

In [68]:
arr2[0:5] 

array([[64, 53, 73, 65, 53, 26, 16, 34, 25, 38],
       [80, 51, 52,  3, 94, 77,  8, 75, 75, 22],
       [10, 90, 28, 29, 48,  7, 88,  0, 43,  1],
       [16,  6, 37, 22, 54, 23, 97, 12, 20, 80],
       [63, 97, 48, 35, 79, 37, 85, 88, 13, 33]], dtype=int32)

In [69]:
arr2

array([[64, 53, 73, 65, 53, 26, 16, 34, 25, 38],
       [80, 51, 52,  3, 94, 77,  8, 75, 75, 22],
       [10, 90, 28, 29, 48,  7, 88,  0, 43,  1],
       [16,  6, 37, 22, 54, 23, 97, 12, 20, 80],
       [63, 97, 48, 35, 79, 37, 85, 88, 13, 33],
       [73, 19, 95, 76, 23, 98, 66, 13, 99,  0],
       [52,  3, 49, 53, 25, 61, 40, 94, 30, 79],
       [14, 10, 26, 90, 79, 34, 12, 86, 91,  6],
       [87, 60, 39, 33, 17, 52, 37, 36, 16, 44],
       [ 5, 70, 65, 19, 56,  4, 51, 65, 88, 89]], dtype=int32)

In [70]:
arr2[1,4] 

np.int32(94)

In [71]:
arr2[-5,5] 

np.int32(98)

In [72]:
arr2[-5,-5] 

np.int32(98)

In [73]:
arr2[-5,-5]

np.int32(98)

In [74]:
arr2[-1,-2]

np.int32(88)

In [75]:
arr2[::-1]

array([[ 5, 70, 65, 19, 56,  4, 51, 65, 88, 89],
       [87, 60, 39, 33, 17, 52, 37, 36, 16, 44],
       [14, 10, 26, 90, 79, 34, 12, 86, 91,  6],
       [52,  3, 49, 53, 25, 61, 40, 94, 30, 79],
       [73, 19, 95, 76, 23, 98, 66, 13, 99,  0],
       [63, 97, 48, 35, 79, 37, 85, 88, 13, 33],
       [16,  6, 37, 22, 54, 23, 97, 12, 20, 80],
       [10, 90, 28, 29, 48,  7, 88,  0, 43,  1],
       [80, 51, 52,  3, 94, 77,  8, 75, 75, 22],
       [64, 53, 73, 65, 53, 26, 16, 34, 25, 38]], dtype=int32)

In [76]:
arr2[::-2] 

array([[ 5, 70, 65, 19, 56,  4, 51, 65, 88, 89],
       [14, 10, 26, 90, 79, 34, 12, 86, 91,  6],
       [73, 19, 95, 76, 23, 98, 66, 13, 99,  0],
       [16,  6, 37, 22, 54, 23, 97, 12, 20, 80],
       [80, 51, 52,  3, 94, 77,  8, 75, 75, 22]], dtype=int32)

In [77]:
arr2[::-3]

array([[ 5, 70, 65, 19, 56,  4, 51, 65, 88, 89],
       [52,  3, 49, 53, 25, 61, 40, 94, 30, 79],
       [16,  6, 37, 22, 54, 23, 97, 12, 20, 80],
       [64, 53, 73, 65, 53, 26, 16, 34, 25, 38]], dtype=int32)

In [78]:
arr2[:-3] 

array([[64, 53, 73, 65, 53, 26, 16, 34, 25, 38],
       [80, 51, 52,  3, 94, 77,  8, 75, 75, 22],
       [10, 90, 28, 29, 48,  7, 88,  0, 43,  1],
       [16,  6, 37, 22, 54, 23, 97, 12, 20, 80],
       [63, 97, 48, 35, 79, 37, 85, 88, 13, 33],
       [73, 19, 95, 76, 23, 98, 66, 13, 99,  0],
       [52,  3, 49, 53, 25, 61, 40, 94, 30, 79]], dtype=int32)

In [79]:
arr.max() 

np.int64(5)

In [80]:
arr.min()

np.int64(0)

In [81]:
arr.mean()

np.float64(2.5)

In [82]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [83]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

### Masking

In [85]:
mat = np.arange(0,100).reshape(10,10) 

In [87]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [88]:
id(mat)

1639764737648

In [89]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [90]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [91]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [92]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [93]:
mat[mat==50] 

array([50])

In [94]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [95]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Array Manipulation Functions 

In [96]:
# Reshape an array
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (1, 3))  # Reshape to 1x3
print("Reshaped array:", reshaped) 

Reshaped array: [[1 2 3]]


In [97]:
# Reshape an array
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (3, 1))  # Reshape to 1x3
print("Reshaped array:", reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [98]:
# Flatten an array
f1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
flattened = np.ravel(f1)  # Flatten to 1D array
print("Flattened array:", flattened) 

Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [99]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1)  # Transpose the array
print("Transposed array:\n", transposed) 

Transposed array:
 [[1 3]
 [2 4]]


In [100]:
# Stack arrays vertically
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked) 

Stacked arrays:
 [[1 2]
 [3 4]]


In [101]:
# Stack arrays horizontal
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.hstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked) 

Stacked arrays:
 [1 2 3 4]


## Mathematical Functions

In [102]:
# Add two arrays
g = np.array([1, 2, 3, 4])
added = np.add(g, 2)  # Add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [103]:
# Square each element
squared = np.power(g, 2)  # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [104]:
# Square root of each element
sqrt_val = np.sqrt(g)  # Square root of each element
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [105]:
print(a)
print(g)

[1 2 3 4 9]
[1 2 3 4]


In [106]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a, g)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

ValueError: shapes (5,) and (4,) not aligned: 5 (dim 0) != 4 (dim 0)

In [107]:
print(a)
print(a1) 

[1 2 3 4 9]
[1 2 3]


In [109]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a1, a3)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


## Statistical Functions

In [110]:
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [111]:
# Standard deviation of an array
var = np.var(s)
print("Variance of s :", var)

Variance of s : 1.25


In [112]:
# Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [113]:
s

array([1, 2, 3, 4])

In [114]:
# Minimum element of an array
minimum = np.min(s) 
print("Min of s:", minimum)

Min of s: 1


In [115]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


## Linear Algebra Fuctions

In [116]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]]) 
matrix

array([[1, 2],
       [3, 4]])

## Random Sampling Functions

In [117]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals) 

Random values: [0.50605817 0.91415761 0.22614153]


In [118]:
# Set seed for reproducibility
np.random.seed(0) 

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [119]:
# Generate random integers 
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints) 

Random integers: [3 7 9 3 5]


In [120]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


## Boolean and Logical Functions

In [121]:
# Check if all elements are True

# all
logical_test = np.array([True, False, True]) 
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [122]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [123]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [124]:
# Check if all elements are True
logical_test = np.array([False, True, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [125]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: True


## Set Operations

In [126]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [127]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


## Array Attribute Functions

In [128]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


## Other Functions

In [129]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [130]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [131]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False


# Complete